// Copyright (c) 2021 David Helkowski
// Anti-Corruption License

// Generated by https://github.com/nanoscopic/mobdev_dump_errs
#ifndef __MOBDEV_ERR
#define __MOBDEV_ERR

typedef struct {
  const char *name;
  const char *error;
  const uint32_t num;
} mobdev_err;

mobdev_err *mobdev_geterr(uint32_t num);
#endif
